"""beyond32 -- superconducting pairing channels of the icosahedral group.

Companion code of

    Eva Moss, "Beyond the 32: Superconducting Pairing Channels of the Icosahedral
    Group -- Classification, Approximant Branching, and Ginzburg-Landau Theory for
    Quasicrystals" (2026).

Every numerical table (Tables 1-8 and Table 10 of Appendix B) and every displayed result of
the main text (Eqs. 4-23) is regenerated by ``beyond32 all``.  All group theory is exact
over Q(sqrt 5) (sympy; Q(sqrt3, sqrt5) in the H channel; Q(sqrt 3) for the dodecagonal
point group D6d of Appendix B); floating point is used only for the numerical
minimisations (BFGS restarts, the Nelder-Mead fit of kappa and phi_0), the node search,
the isotropy fixed spaces (SVD) and the quadrature of the Table 8 coordinates.
"""

__version__ = "1.1.0"
