"""beyond32 -- superconducting pairing channels of the icosahedral group.

Companion code of

    Eva Moss, "Beyond the 32: Superconducting Pairing Channels of the Icosahedral
    Group -- Classification, Approximant Branching, and Ginzburg-Landau Theory for
    Quasicrystals" (2026).

Every table and equation of the paper is regenerated by ``beyond32 all``.  All group
theory is exact over Q(sqrt 5) (sympy); floating point is used only for the numerical
minimisations, the node search and the isotropy-subgroup solve.
"""

__version__ = "1.0.0"
