"""The dodecagonal group D12: in-plane harmonics, enforced nodes, Sym^2 and circle
weak coupling (Appendix B / Section 10 of the paper).

The two-dimensional dodecagonal point group D12 (order 24) is generated by the
twelve-fold rotation about the axis z and a two-fold rotation about an in-plane
axis.  In the polar angle phi of the plane its elements act as

* ``R_k``: phi -> phi + 2 pi k/12            (k = 0..11, the rotations, subgroup C12),
* ``P_k``: phi -> 2 theta_k - phi, theta_k = k pi/12   (k = 0..11, in-plane two-fold rotations).

The two-fold axes fall into two classes: C2' along the angles theta_k = k pi/6
(k even in the legacy numbering: 0, 30, 60, ... degrees) and C2'' along
pi/12 + k pi/6 (k odd: 15, 45, 75, ... degrees).  Together with E, C12, C6, C4,
C3, C12^5 and C2 (= R_6) this gives nine classes and nine irreps
A1, A2, B1, B2, E1, ..., E5 (sum of d^2 = 1+1+1+1+4*5 = 24).

What is computed here (and in which test it is pinned)

* the group itself: elements, the exact composition law obtained by composing the
  maps phi -> g(phi) with sympy, the multiplication table, the conjugacy classes
  and the exact 3x3 SO(3) matrices of the elements (``elements``, ``compose``,
  ``multiplication_table``, ``conjugacy_classes``, ``matrix``);
* the character table with exact entries (2 cos(2 pi m k/12) evaluates to
  0, +-1, +-sqrt3, +-2), ``character_table_D12``; the E_m rows are the traces of
  the exact 2x2 matrices of the action on span{cos m phi, sin m phi}
  (``pair_matrix``), the one-dimensional rows are the four sign characters;
* the assignment of the in-plane harmonics cos m phi, sin m phi (the constant for
  m = 0) to irreps by m mod 12 -- Eq. (24) of the paper -- from the exact
  character of the two-dimensional representation (``harmonic_irreps``,
  ``harmonic_assignment``, ``residue_table``);
* the symmetry-enforced nodes: a gap function in an irrep Gamma is forced to
  vanish along a direction n unless Gamma restricted to the stabiliser of n
  contains the trivial representation.  The stabiliser of an in-plane C2 axis is
  {E, P_k}, so a one-dimensional irrep with chi(P_k) = -1 has a node there; the
  stabiliser of the twelve-fold axis is C12, so only A1 and A2 survive on it
  (``enforced_nodes``, ``node_table``);
* Sym^2 E_m by characters, (chi(g)^2 + chi(g^2))/2, and the number of
  independent quartic Ginzburg-Landau invariants sum_lambda m_lambda^2
  (``sym2_decomposition``, ``quartic_invariant_count``);
* the weak-coupling ratio on the circle R = <|Delta|^4>/<|Delta|^2>^2 for the real
  state Delta = cos m phi (R = 3/2) and the chiral state Delta = e^{i m phi}
  (R = 1), by exact sympy integration (``weak_coupling_ratio``).

The characters of D12 live in Q(sqrt 3), not in Q(sqrt 5); the field helpers of
``_exact`` therefore do not apply and canonicalisation is done with ``sympy.expand``
(products of the square roots evaluate automatically).  Everything here is exact.
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from typing import Dict, List, Sequence, Tuple

import sympy as sp
from sympy import Matrix, Rational, S, pi

from .groups import CharacterTable

N = 12                                    # the twelve-fold rotation order
ORDER = 2 * N                             # |D12| = 24
IRREPS_D12 = ("A1", "A2", "B1", "B2", "E1", "E2", "E3", "E4", "E5")
CLASSES_D12 = ("E", "C12", "C6", "C4", "C3", "C12^5", "C2", "C2'", "C2''")
CLASS_SIZES_D12 = (1, 2, 2, 2, 2, 2, 1, 6, 6)
TWOFOLD_TYPES = ("C2'", "C2''")

ANGLE = sp.Symbol("phi", real=True)      # polar angle in the plane


def _canon3(e) -> sp.Expr:
    """Canonical form of a number in Q(sqrt3) (or Q(sqrt2, sqrt3)): expand, so that products
    of the radicals evaluate and rationals combine."""
    return sp.expand(e)


# --------------------------------------------------------------------------- elements
@dataclass(frozen=True)
class D12Element:
    """One element of D12: a rotation ``R_k`` (kind 'R') or an in-plane two-fold rotation
    ``P_k`` (kind 'P') about the axis at angle theta_k = k pi/12; k = 0..11."""
    kind: str
    k: int

    def __post_init__(self):
        if self.kind not in ("R", "P") or not 0 <= self.k < N:
            raise ValueError(f"bad D12 element {self.kind}_{self.k}")

    @property
    def label(self) -> str:
        return f"{self.kind}_{self.k}"

    def __str__(self) -> str:
        return self.label

    @property
    def is_rotation(self) -> bool:
        return self.kind == "R"

    @property
    def is_twofold(self) -> bool:
        return self.kind == "P"

    @property
    def twofold_type(self) -> str:
        """"C2'" (axis at k pi/6, k even) or "C2''" (axis at pi/12 + k pi/6, k odd)."""
        if not self.is_twofold:
            raise ValueError(f"{self.label} is not an in-plane two-fold rotation")
        return TWOFOLD_TYPES[self.k % 2]

    @property
    def axis_angle(self) -> sp.Expr:
        """theta_k = k pi/12, the direction of the two-fold axis of P_k."""
        if not self.is_twofold:
            raise ValueError(f"{self.label} is not an in-plane two-fold rotation")
        return self.k * pi / N

    def act(self, phi):
        """The image of the polar angle phi: phi + 2 pi k/12 (R_k) or 2 theta_k - phi (P_k)."""
        if self.kind == "R":
            return phi + 2 * pi * self.k / N
        return 2 * (self.k * pi / N) - phi


def act(e: D12Element, phi):
    """g(phi) for g in D12 (module-level alias of ``D12Element.act``)."""
    return e.act(phi)


@lru_cache(maxsize=None)
def elements() -> Tuple[D12Element, ...]:
    """The 24 elements in the legacy order R_0, ..., R_11, P_0, ..., P_11 (R_0 = E)."""
    return tuple(D12Element("R", k) for k in range(N)) + tuple(D12Element("P", k) for k in range(N))


def identity() -> D12Element:
    return elements()[0]


def index_of(e: D12Element) -> int:
    return (0 if e.kind == "R" else N) + e.k


def _identify(expr) -> D12Element:
    """The element whose action phi -> +-phi + c equals the given exact expression."""
    expr = sp.expand(expr)
    sign = expr.coeff(ANGLE)
    if sign not in (1, -1):
        raise ValueError(f"not an element of D12: {expr}")
    const = sp.expand(expr - sign * ANGLE)
    q = sp.Rational(sp.expand(const / (2 * pi / N)))      # exact: pi cancels
    if not q.is_Integer:
        raise ValueError(f"not an element of D12: {expr}")
    return D12Element("R" if sign == 1 else "P", int(q) % N)


def compose(a: D12Element, b: D12Element) -> D12Element:
    """The product a b (apply b first, then a), obtained by composing the maps on phi."""
    return _identify(a.act(b.act(ANGLE)))


@lru_cache(maxsize=None)
def multiplication_table() -> Tuple[Tuple[int, ...], ...]:
    """mult[i][j] = index of g_i g_j in ``elements()``."""
    els = elements()
    return tuple(tuple(index_of(compose(a, b)) for b in els) for a in els)


@lru_cache(maxsize=None)
def inverse_table() -> Tuple[int, ...]:
    mult = multiplication_table()
    return tuple(next(j for j in range(ORDER) if mult[i][j] == 0) for i in range(ORDER))


def inverse(e: D12Element) -> D12Element:
    return elements()[inverse_table()[index_of(e)]]


def _class_label(e: D12Element) -> str:
    """Class label of an element from its type and rotation angle."""
    if e.is_twofold:
        return e.twofold_type
    r = min(e.k, N - e.k)
    return {0: "E", 1: "C12", 2: "C6", 3: "C4", 4: "C3", 5: "C12^5", 6: "C2"}[r]


@lru_cache(maxsize=None)
def conjugacy_classes() -> Dict[str, Tuple[int, ...]]:
    """The nine conjugacy classes computed from the multiplication table, labelled as in
    ``CLASSES_D12`` (label -> indices into ``elements()``)."""
    els = elements()
    mult = multiplication_table()
    inv = inverse_table()
    seen = set()
    classes: Dict[str, Tuple[int, ...]] = {}
    for i in range(ORDER):
        if i in seen:
            continue
        orbit = sorted({mult[mult[h][i]][inv[h]] for h in range(ORDER)})
        seen.update(orbit)
        labels = {_class_label(els[j]) for j in orbit}
        if len(labels) != 1:
            raise ValueError(f"class {orbit} mixes labels {labels}")
        classes[labels.pop()] = tuple(orbit)
    if set(classes) != set(CLASSES_D12):
        raise ValueError(f"unexpected class structure {sorted(classes)}")
    ordered = {c: classes[c] for c in CLASSES_D12}
    if tuple(len(v) for v in ordered.values()) != CLASS_SIZES_D12:
        raise ValueError("unexpected class sizes")
    return ordered


def class_of(e: D12Element) -> str:
    i = index_of(e)
    for c, idx in conjugacy_classes().items():
        if i in idx:
            return c
    raise ValueError(e)


@lru_cache(maxsize=None)
def class_representatives() -> Tuple[D12Element, ...]:
    """The first element of each class, in the order of ``CLASSES_D12``."""
    els = elements()
    return tuple(els[idx[0]] for idx in conjugacy_classes().values())


@lru_cache(maxsize=None)
def matrix(e: D12Element) -> Matrix:
    """The exact 3x3 rotation matrix of the element in SO(3): R_k rotates about z by
    2 pi k/12, P_k is the two-fold rotation about the in-plane axis
    (cos theta_k, sin theta_k, 0) (it sends z -> -z)."""
    if e.is_rotation:
        a = 2 * pi * e.k / N
        return Matrix([[sp.cos(a), -sp.sin(a), 0], [sp.sin(a), sp.cos(a), 0], [0, 0, 1]])
    t2 = 2 * e.axis_angle
    return Matrix([[sp.cos(t2), sp.sin(t2), 0], [sp.sin(t2), -sp.cos(t2), 0], [0, 0, -1]])


# --------------------------------------------------------------------------- the pair representation
@lru_cache(maxsize=None)
def _root_of_unity(n: int) -> sp.Expr:
    """exp(2 pi i n/12) as an exact number in Q(sqrt3, i)."""
    w = sp.cos(2 * pi / N) + sp.I * sp.sin(2 * pi / N)
    return _canon3(w ** (n % N))


def _laurent_image(n: int, e: D12Element) -> Tuple[sp.Expr, int]:
    """The image of u^n = exp(i n phi) under phi -> e(phi), as (coefficient, exponent):
    R_k: u^n -> w^{kn} u^n;  P_k: u^n -> w^{kn} u^{-n}  (w = exp(2 pi i/12), 2 theta_k = 2 pi k/12)."""
    if e.is_rotation:
        return _root_of_unity(e.k * n), n
    return _root_of_unity(e.k * n), -n


def _pullback_matrix(m: int, e: D12Element) -> Matrix:
    """Matrix of f -> f o e on span{cos m phi, sin m phi} (column j = image of basis
    function j), computed exactly through u = exp(i phi)."""
    if m < 1:
        raise ValueError("m must be >= 1")
    half, half_i = Rational(1, 2), 1 / (2 * sp.I)
    basis = ({m: half, -m: half}, {m: half_i, -m: -half_i})     # cos m phi, sin m phi as Laurent dicts
    cols = []
    for f in basis:
        img: Dict[int, sp.Expr] = {}
        for n, c in f.items():
            coeff, exp_ = _laurent_image(n, e)
            img[exp_] = _canon3(img.get(exp_, 0) + c * coeff)
        cp, cm = img.get(m, S(0)), img.get(-m, S(0))
        if set(img) - {m, -m}:
            raise ValueError("image leaves span{cos m phi, sin m phi}")
        alpha = _canon3(cp + cm)              # coefficient of cos m phi
        beta = _canon3(sp.I * (cp - cm))      # coefficient of sin m phi
        if alpha.has(sp.I) or beta.has(sp.I):
            raise ValueError("non-real pair matrix")
        cols.append((alpha, beta))
    return Matrix([[cols[0][0], cols[1][0]], [cols[0][1], cols[1][1]]])


@lru_cache(maxsize=None)
def pair_matrix(m: int, e: D12Element) -> Matrix:
    """The exact 2x2 matrix of rho(e) on span{cos m phi, sin m phi}, m >= 1, with
    (rho(g) f)(phi) = f(g^-1 phi) as in ``harmonics.act`` (so that rho is a homomorphism).
    Rotations give the rotation matrix by 2 pi m k/12, the P_k give reflections of trace 0."""
    return _pullback_matrix(m, inverse(e))


def pair_character(m: int, e: D12Element) -> sp.Expr:
    """Character of the representation on the in-plane harmonics of order m: the trace of
    ``pair_matrix`` for m >= 1 (2 cos(2 pi m k/12) on R_k, 0 on P_k); 1 for the constant
    (m = 0)."""
    if m == 0:
        return S(1)
    return _canon3(pair_matrix(m, e).trace())


def harmonic_character(m: int) -> Tuple[sp.Expr, ...]:
    """The character of span{cos m phi, sin m phi} (m >= 1) or of the constant (m = 0) on the
    classes of D12."""
    return tuple(pair_character(m, e) for e in class_representatives())


# --------------------------------------------------------------------------- character table
def _one_dim_character(name: str, e: D12Element) -> sp.Expr:
    """The four sign characters: A1 trivial; A2 = -1 on all in-plane two-fold rotations;
    B1: (-1)^k on R_k, +1 on C2' (k even), -1 on C2''; B2: (-1)^k on R_k, -1 on C2', +1 on C2''."""
    if name == "A1":
        return S(1)
    if name == "A2":
        return S(1) if e.is_rotation else S(-1)
    if name == "B1":
        return S((-1) ** e.k)
    if name == "B2":
        return S((-1) ** e.k) if e.is_rotation else S(-((-1) ** e.k))
    raise KeyError(name)


@dataclass(frozen=True)
class D12CharacterTable(CharacterTable):
    """``groups.CharacterTable`` with the inner product taken in Q(sqrt3)."""

    def inner(self, u: Sequence, v: Sequence) -> sp.Expr:
        return _canon3(sum(s * sp.conjugate(a) * b for s, a, b in zip(self.sizes, u, v)) / self.order)


@lru_cache(maxsize=None)
def character_table_D12() -> D12CharacterTable:
    """The character table of D12 (Appendix B), classes in the order ``CLASSES_D12``:
    E, 2 C12, 2 C6, 2 C4, 2 C3, 2 C12^5, C2, 6 C2', 6 C2''.  The E_m rows are the traces
    of the exact matrices on span{cos m phi, sin m phi}; the one-dimensional rows are the sign
    characters of ``_one_dim_character``.  Orthonormality is checked."""
    reps = class_representatives()
    chars: Dict[str, Tuple[sp.Expr, ...]] = {}
    for name in ("A1", "A2", "B1", "B2"):
        chars[name] = tuple(_one_dim_character(name, e) for e in reps)
    for m in range(1, N // 2):
        chars[f"E{m}"] = tuple(pair_character(m, e) for e in reps)
    T = D12CharacterTable("D12", CLASSES_D12, CLASS_SIZES_D12, chars)
    if not T.is_orthonormal():
        raise ValueError("D12 character table is not orthonormal")
    return T


def character(irrep: str, e: D12Element) -> sp.Expr:
    """chi_Gamma(g) for an element g."""
    return character_table_D12().chars[irrep][CLASSES_D12.index(class_of(e))]


def is_class_function(values: Sequence) -> bool:
    """True if a tuple of 24 values (element order) is constant on the conjugacy classes."""
    return all(len({values[i] for i in idx}) == 1 for idx in conjugacy_classes().values())


def is_one_dim_representation(irrep: str) -> bool:
    """chi(ab) = chi(a) chi(b) on all 24 x 24 products (for a one-dimensional irrep)."""
    els = elements()
    mult = multiplication_table()
    chi = [character(irrep, e) for e in els]
    return all(chi[mult[i][j]] == chi[i] * chi[j] for i in range(ORDER) for j in range(ORDER))


# --------------------------------------------------------------------------- harmonics -> irreps
def harmonic_irreps(m: int) -> Dict[str, int]:
    """Irrep content of the in-plane harmonics of order m (span{cos m phi, sin m phi} for
    m >= 1, the constant for m = 0), decomposed with the character table."""
    return character_table_D12().decompose(harmonic_character(m))


def harmonic_assignment(mmax: int = 12) -> Dict[int, Dict[str, int]]:
    """{m: irrep content} for m = 0..mmax (the legacy script printed m = 0..12)."""
    return {m: harmonic_irreps(m) for m in range(mmax + 1)}


def residue_table() -> Dict[int, Dict[str, int]]:
    """The assignment by m mod 12 for m >= 1 (Eq. 24 of the paper): residue r -> irrep
    content, computed from m = 12 (r = 0), 1, ..., 11 and checked against m = 13..24."""
    out = {}
    for r in range(N):
        m = r if r else N
        dec = harmonic_irreps(m)
        if harmonic_irreps(m + N) != dec:
            raise ValueError(f"assignment is not periodic in m mod 12 at m = {m}")
        out[r] = dec
    return out


# --------------------------------------------------------------------------- enforced nodes
def in_plane_direction(j: int) -> Matrix:
    """Unit vector in the plane at angle j pi/12, j = 0..23 (the 24 directions of the twelve
    in-plane two-fold axes; j even: C2', j odd: C2'')."""
    theta = j * pi / N
    return Matrix([sp.cos(theta), sp.sin(theta), 0])


def direction_type(j: int) -> str:
    return TWOFOLD_TYPES[j % 2]


def twelvefold_axis() -> Matrix:
    return Matrix([0, 0, 1])


def stabiliser(n: Matrix) -> Tuple[int, ...]:
    """Indices of the elements whose SO(3) matrix fixes the direction n (exact)."""
    return tuple(i for i, e in enumerate(elements())
                 if (matrix(e) * n - n).applyfunc(_canon3) == sp.zeros(3, 1))


@lru_cache(maxsize=None)
def _stabilisers() -> Tuple[Tuple[Tuple[int, ...], ...], Tuple[int, ...]]:
    """(stabilisers of the 24 in-plane directions, stabiliser of the twelve-fold axis)."""
    plane = tuple(stabiliser(in_plane_direction(j)) for j in range(2 * N))
    return plane, stabiliser(twelvefold_axis())


def trivial_multiplicity(irrep: str, subgroup: Sequence[int]) -> sp.Expr:
    """Multiplicity of the trivial representation in Gamma restricted to a subgroup
    (given by element indices): (1/|S|) sum_{s in S} chi_Gamma(s)."""
    els = elements()
    return _canon3(sum(character(irrep, els[i]) for i in subgroup) / len(subgroup))


@dataclass(frozen=True)
class NodeRecord:
    """Symmetry-enforced nodes of a gap function transforming as one irrep of D12.

    ``trivial_*`` are the multiplicities of the trivial representation in the irrep restricted
    to the stabiliser of a C2' direction ({E, P_0}), of a C2'' direction ({E, P_1}) and of the
    twelve-fold axis (C12).  A node is enforced where that multiplicity is zero.
    ``node_angles`` lists the exact in-plane angles (multiples of pi) with an enforced node."""
    irrep: str
    trivial_C2prime: int
    trivial_C2double: int
    trivial_axis: int
    node_C2prime: bool
    node_C2double: bool
    node_axis: bool
    node_angles: Tuple[sp.Expr, ...]

    @property
    def n_in_plane_nodes(self) -> int:
        return len(self.node_angles)


@lru_cache(maxsize=None)
def enforced_nodes() -> Dict[str, NodeRecord]:
    """For every irrep, the nodes enforced by symmetry (Appendix B): on the C2' directions,
    on the C2'' directions and on the twelve-fold axis, from the trivial-character criterion
    on the stabilisers.  A2 vanishes on all 24 in-plane axis directions, B2 on the twelve C2',
    B1 on the twelve C2'', the E_m nowhere in the plane; on the twelve-fold axis only A1 and A2
    are non-vanishing."""
    plane_stabs, axis_stab = _stabilisers()
    out = {}
    for irrep in IRREPS_D12:
        mults = [trivial_multiplicity(irrep, s) for s in plane_stabs]
        if not all(x.is_Integer for x in mults):
            raise ValueError("non-integral trivial multiplicity")
        by_type = {t: {int(mults[j]) for j in range(2 * N) if direction_type(j) == t}
                   for t in TWOFOLD_TYPES}
        if any(len(v) != 1 for v in by_type.values()):
            raise ValueError("directions of one type disagree")
        t_prime, t_double = (by_type[t].pop() for t in TWOFOLD_TYPES)
        t_axis = trivial_multiplicity(irrep, axis_stab)
        if not t_axis.is_Integer:
            raise ValueError("non-integral trivial multiplicity")
        angles = tuple(j * pi / N for j in range(2 * N) if mults[j] == 0)
        out[irrep] = NodeRecord(irrep, t_prime, t_double, int(t_axis),
                                t_prime == 0, t_double == 0, int(t_axis) == 0, angles)
    return out


def node_table() -> List[Dict[str, object]]:
    """Plain-data version of ``enforced_nodes`` (one dict per irrep)."""
    rows = []
    for irrep, r in enforced_nodes().items():
        rows.append({"irrep": irrep,
                     "chi_C2prime": str(character(irrep, D12Element("P", 0))),
                     "chi_C2double": str(character(irrep, D12Element("P", 1))),
                     "trivial_C2prime": r.trivial_C2prime,
                     "trivial_C2double": r.trivial_C2double,
                     "trivial_axis": r.trivial_axis,
                     "node_C2prime": r.node_C2prime,
                     "node_C2double": r.node_C2double,
                     "node_axis": r.node_axis,
                     "n_in_plane_nodes": r.n_in_plane_nodes})
    return rows


# --------------------------------------------------------------------------- Sym^2 E_m
def sym2_character(m: int) -> Tuple[sp.Expr, ...]:
    """Character of Sym^2 E_m on the classes: (chi(g)^2 + chi(g^2))/2, with g^2 from the
    multiplication table."""
    els = elements()
    mult = multiplication_table()
    out = []
    for e in class_representatives():
        i = index_of(e)
        sq = els[mult[i][i]]
        out.append(_canon3((pair_character(m, e) ** 2 + pair_character(m, sq)) / 2))
    return tuple(out)


def sym2_decomposition(m: int) -> Dict[str, int]:
    """Sym^2 E_m = A1 + E_{2m} for m = 1, 2, 4, 5 (E_8 = E_4, E_10 = E_2) and
    A1 + B1 + B2 for m = 3 (E_6 = B1 + B2)."""
    if not 1 <= m <= N // 2 - 1:
        raise ValueError("E_m exists for m = 1..5")
    return character_table_D12().decompose(sym2_character(m))


def quartic_invariant_count(m: int) -> int:
    """Number of independent quartic invariants |Delta|^4 of the E_m channel: sum over the
    irreps lambda of Sym^2 E_m of m_lambda^2 (all irreps of D12 are real): 2, 2, 3, 2, 2."""
    return sum(v * v for v in sym2_decomposition(m).values())


def sym2_table() -> Dict[str, Dict[str, int]]:
    return {f"E{m}": sym2_decomposition(m) for m in range(1, N // 2)}


# --------------------------------------------------------------------------- weak coupling on the circle
def circle_average(f) -> sp.Expr:
    """(1/2 pi) int_0^{2 pi} f(phi) dphi, exactly."""
    return sp.simplify(sp.integrate(f, (ANGLE, 0, 2 * pi)) / (2 * pi))


def circle_ratio(delta) -> sp.Expr:
    """R = <|Delta|^4> / <|Delta|^2>^2 on the circle for a gap function Delta(phi)."""
    a2 = sp.expand(delta * sp.conjugate(delta))
    return sp.simplify(circle_average(sp.expand(a2 ** 2)) / circle_average(a2) ** 2)


def weak_coupling_ratio(m: int = 1, chiral: bool = False) -> sp.Expr:
    """The weak-coupling ratio quoted in Appendix B: 3/2 for the real state Delta = cos m phi
    and 1 for the chiral state Delta = exp(i m phi) (|Delta| constant)."""
    if m < 1:
        raise ValueError("m must be >= 1")
    delta = sp.exp(sp.I * m * ANGLE) if chiral else sp.cos(m * ANGLE)
    return circle_ratio(delta)


# --------------------------------------------------------------------------- formatting
def format_decomposition(dec: Dict[str, int]) -> str:
    return character_table_D12().format(dec)


def format_character_table() -> Dict[str, object]:
    """{"classes": [...], "sizes": [...], "rows": [{"irrep": name, "chars": [str, ...]}]}."""
    T = character_table_D12()
    return {"classes": list(T.classes), "sizes": list(T.sizes),
            "rows": [{"irrep": name, "chars": [str(c) for c in row]} for name, row in T.chars.items()]}


def format_assignment(mmax: int = 12) -> List[Dict[str, object]]:
    """Rows {"m": m, "residue": m mod 12, "irreps": "E1"} for m = 0..mmax."""
    return [{"m": m, "residue": m % N, "irreps": format_decomposition(dec)}
            for m, dec in harmonic_assignment(mmax).items()]


def format_residue_table() -> List[Dict[str, object]]:
    """Eq. (24): rows {"residue": r, "irreps": ...} for r = m mod 12, m >= 1."""
    return [{"residue": r, "irreps": format_decomposition(dec)} for r, dec in residue_table().items()]


def format_node_table() -> List[Dict[str, object]]:
    """Rows {"irrep", "C2'", "C2''", "axis", "in-plane nodes"} with "node" / "-" entries, as in
    the enforced-node discussion of Appendix B."""
    tag = {True: "node", False: "-"}
    return [{"irrep": r.irrep, "C2'": tag[r.node_C2prime], "C2''": tag[r.node_C2double],
             "axis": tag[r.node_axis], "in-plane nodes": r.n_in_plane_nodes}
            for r in enforced_nodes().values()]


def format_sym2_table() -> List[Dict[str, object]]:
    return [{"irrep": name, "Sym^2": format_decomposition(dec), "quartic invariants": sum(v * v for v in dec.values())}
            for name, dec in sym2_table().items()]


def summary() -> Dict[str, object]:
    """Everything of Appendix B as plain data (for results.json / the LaTeX emitter)."""
    T = character_table_D12()
    return {"order": T.order, "irreps": list(T.irreps),
            "character_table": format_character_table(),
            "assignment": format_assignment(),
            "residues": format_residue_table(),
            "nodes": format_node_table(),
            "sym2": format_sym2_table(),
            "weak_coupling": {"real": str(weak_coupling_ratio(1, chiral=False)),
                              "chiral": str(weak_coupling_ratio(1, chiral=True))}}
