"""The dodecagonal point group D6d = -12m2 of the Ta1.6Te quasicrystal: pairing functions on
the in-plane circle (Appendix B and Table 10 of the paper).

The point group of the dodecagonal quasicrystal Ta1.6Te is D6d (Hermann-Mauguin -12m2;
Yamamoto, Acta Cryst. A 60, 142 (2004)), of order 24.  It contains no inversion, no
horizontal mirror and no true twelve-fold rotation: its principal operation is the
twelve-fold rotoreflection S12 = sigma_h C12.  In Yamamoto's orientation the group is
generated by

    S12 = diag(1, 1, -1) . R_z(30 deg)      (the rotoreflection about z),
    C2' = the two-fold rotation about the in-plane axis at 15 deg,

so that the six vertical mirror planes sigma_d contain the in-plane directions 30 deg . j
(the framework edges) and the six two-fold axes C2' lie at 15 deg + 30 deg . j.  The 24
elements are the closure of the two generators as exact 3x3 matrices over Q(sqrt 3)
(``elements``, ``matrix``); every element is diag(O, eps) with O in O(2) and eps = +-1:

* ``S_k`` = S12^k (k = 0..11): in-plane rotation by 30 k deg, eps = (-1)^k
  (k even: the rotations E, C6, C3, C2, ...; k odd: the rotoreflections S12, S4, S12^5, ...),
* ``P_k`` (k = 0..11): in-plane reflection across the line at 15 k deg, eps = (-1)^k
  (k even: the mirror sigma_d containing the direction 15 k deg; k odd: the two-fold
  rotation C2' about the axis at 15 k deg).

Nine conjugacy classes, E, 2 S12, 2 C6, 2 S4, 2 C3, 2 S12^5, C2, 6 C2', 6 sigma_d, and nine
irreps A1, A2, B1, B2, E1, ..., E5 (sum of d^2 = 24).  The one-dimensional characters are
read off the matrices, B1(g) = det g, B2(g) = g_zz, A2 = B1 B2 -- so B1 is +1 on the
two-fold axes and -1 on the mirrors, B2 the reverse, A2 is -1 on both -- and E_m is the
trace of the action on span{cos m phi, sin m phi} (``character_table_D6d``).  Abstractly
D6d is isomorphic to the dihedral group of order 24, but as a point group it is not D12:
half of its operations are improper.

Pair functions on the in-plane circle k = (cos phi, sin phi, 0)
--------------------------------------------------------------
The singlet gap psi(phi) transforms as a scalar, psi -> psi(g^-1 k), and the triplet
d-vector as an axial vector, d -> det(g) g d(g^-1 k).  For each harmonic order m the module
builds the exact representation matrices on the sectors

* ``singlet``:          span{cos m phi, sin m phi}                 (even m in the paper),
* ``triplet_inplane``:  span{cos m phi, sin m phi} x {e_x, e_y}    (odd m),
* ``triplet_z``:        span{cos m phi, sin m phi} e_z             (odd m),

decomposes them with the character table and computes the basis functions of every irrep
from the exact isotypic projectors (the reduced row echelon form of their image, so that
the basis functions are canonical): Table 10 (``sector_decomposition``, ``sector_basis``,
``table10``).  Pinned in the tests:

* singlet: m = 0 -> A1, +-2 -> E2, +-4 -> E4, +-6 -> B1 + B2 (sin 6 phi in B1, cos 6 phi in B2);
* triplet, in-plane: m = +-1 -> B1 + B2 + E4, +-3 -> E2 + E4, +-5 -> A1 + A2 + E2;
  d_z: m = +-1 -> E1, +-3 -> E3, +-5 -> E5;
* the antisymmetric spin-orbit vector g(k) (odd in k, axial) has A1 content only in the
  in-plane m = +-5 sector -- within the range |m| <= 6 of Table 10; the sectors depend on
  m mod 12 only, so m = 7 = -5 (mod 12) is the same E5 sector -- with
  g ~ (sin 5 phi, cos 5 phi, 0), and no g_z component for any odd m
  (``asoc_A1_content``, ``asoc_vector``);
* the restriction to the approximant point group D2d = -42m generated by S4 = S12^3 and the
  two-fold axis at 15 deg: A1 -> A1, A2 -> A2, B1 -> B1, B2 -> B2, E1, E3, E5 -> E,
  E2 -> B1 + B2, E4 -> A1 + A2 (``restriction_to_D2d``);
* the orbit of an in-plane axial vector (a magnetic field) under D6d, with H -> -H
  included, consists of all multiples of 30 deg, so in-plane field-angle dependences have
  period 30 deg (``field_orbit``, ``field_angle_period``).

Everything here is exact: the matrices, characters and projectors live in Q(sqrt 3) (the
rotoreflection S12 brings in cos 30 deg = sqrt3/2), canonicalised with ``sympy.expand`` as
in the rest of the package; the results are integer multiplicities and closed
trigonometric forms.
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from typing import Dict, List, Sequence, Tuple

import sympy as sp
from sympy import ImmutableMatrix, Matrix, S, pi, sqrt

from .groups import CharacterTable

N = 12                                    # the order of the rotoreflection S12
ORDER = 2 * N                             # |D6d| = 24
IRREPS_D6D = ("A1", "A2", "B1", "B2", "E1", "E2", "E3", "E4", "E5")
CLASSES_D6D = ("E", "S12", "C6", "S4", "C3", "S12^5", "C2", "C2'", "sigma_d")
CLASS_SIZES_D6D = (1, 2, 2, 2, 2, 2, 1, 6, 6)
IRREPS_D2D = ("A1", "A2", "B1", "B2", "E")
CLASSES_D2D = ("E", "S4", "C2", "C2'", "sigma_d")
CLASS_SIZES_D2D = (1, 2, 1, 2, 2)
SECTORS = ("singlet", "triplet_inplane", "triplet_z")
SINGLET_M = (0, 2, 4, 6)                  # the harmonic orders listed in Table 10
TRIPLET_M = (1, 3, 5)

ANGLE = sp.Symbol("phi", real=True)      # polar angle in the plane
SQRT3 = sqrt(3)

_S_LABELS = ("E", "S12", "C6", "S4", "C3", "S12^5", "C2", "S12^7", "C3^2", "S4^3", "C6^5", "S12^11")


def _canon3(e) -> sp.Expr:
    """Canonical form of a number in Q(sqrt3) (or Q(sqrt3, i)): expand, so that products of the
    radicals evaluate and rationals combine."""
    return sp.expand(e)


def _canon_matrix(M: Matrix) -> ImmutableMatrix:
    return ImmutableMatrix(M.applyfunc(_canon3))


def _is_zero(e) -> bool:
    return _canon3(e) == 0


# --------------------------------------------------------------------------- the generators
def rotation_z(theta) -> ImmutableMatrix:
    """R_z(theta) (exact for theta a multiple of pi/12)."""
    c, s = _canon3(sp.cos(theta)), _canon3(sp.sin(theta))
    return ImmutableMatrix([[c, -s, 0], [s, c, 0], [0, 0, 1]])


def twofold_about(theta) -> ImmutableMatrix:
    """The two-fold rotation 2 n n^T - 1 about the in-plane axis n = (cos theta, sin theta, 0)."""
    n = Matrix([sp.cos(theta), sp.sin(theta), 0])
    return _canon_matrix(2 * n * n.T - sp.eye(3))


SIGMA_H = ImmutableMatrix.diag(1, 1, -1)          # the horizontal mirror -- not an element of D6d
INVERSION = ImmutableMatrix(-sp.eye(3))           # not an element of D6d either


def generator_S12() -> ImmutableMatrix:
    """S12 = diag(1, 1, -1) . R_z(30 deg), Yamamoto's rotoreflection."""
    return _canon_matrix(SIGMA_H * rotation_z(pi / 6))


def generator_C2prime() -> ImmutableMatrix:
    """The two-fold rotation about the in-plane axis at 15 deg."""
    return twofold_about(pi / 12)


def generators() -> Tuple[ImmutableMatrix, ImmutableMatrix]:
    return generator_S12(), generator_C2prime()


@lru_cache(maxsize=None)
def closure() -> Tuple[ImmutableMatrix, ...]:
    """The group generated by the two generators: breadth-first closure of the exact matrices
    under multiplication, starting from the identity (24 matrices)."""
    gens = generators()
    E = ImmutableMatrix(sp.eye(3))
    found = {E}
    order = [E]
    frontier = [E]
    while frontier:
        new = []
        for M in frontier:
            for g in gens:
                P = _canon_matrix(M * g)
                if P not in found:
                    found.add(P)
                    order.append(P)
                    new.append(P)
        frontier = new
    return tuple(order)


# --------------------------------------------------------------------------- elements
@dataclass(frozen=True)
class D6dElement:
    """One element of D6d: ``S_k`` = S12^k (kind 'S') or ``P_k`` (kind 'P'), the operation whose
    in-plane action is the reflection across the line at angle k pi/12 (the mirror sigma_d for
    k even, the two-fold rotation C2' for k odd); k = 0..11."""
    kind: str
    k: int

    def __post_init__(self):
        if self.kind not in ("S", "P") or not 0 <= self.k < N:
            raise ValueError(f"bad D6d element {self.kind}_{self.k}")

    @property
    def label(self) -> str:
        """Schoenflies label: E, S12, C6, ...; C2'(15), sigma_d(0), ... (angles in degrees)."""
        if self.kind == "S":
            return _S_LABELS[self.k]
        deg = 15 * self.k
        return f"C2'({deg})" if self.k % 2 else f"sigma_d({deg})"

    def __str__(self) -> str:
        return self.label

    @property
    def eps(self) -> int:
        """The z entry g_zz = (-1)^k."""
        return (-1) ** self.k

    @property
    def is_rotoreflection_power(self) -> bool:
        return self.kind == "S"

    @property
    def is_in_plane_reflection(self) -> bool:
        """True for the mirrors sigma_d and the two-fold rotations C2' (both reflect the plane)."""
        return self.kind == "P"

    @property
    def line_angle(self) -> sp.Expr:
        """k pi/12: the direction contained in the mirror plane (k even) or the two-fold axis
        (k odd) of ``P_k``."""
        if self.kind != "P":
            raise ValueError(f"{self.label} has no in-plane mirror line or axis")
        return self.k * pi / N

    def act(self, phi):
        """The induced map of the polar angle: phi + 2 pi k/12 (S_k) or 2 (k pi/12) - phi (P_k)."""
        if self.kind == "S":
            return phi + 2 * pi * self.k / N
        return 2 * self.line_angle - phi


def _parametrised_matrix(e: D6dElement) -> ImmutableMatrix:
    """diag(O, eps): O the in-plane rotation by 2 pi k/12 (S_k) or the reflection across the
    line at k pi/12 (P_k), eps = (-1)^k."""
    t = 2 * pi * e.k / N
    c, s = _canon3(sp.cos(t)), _canon3(sp.sin(t))
    if e.kind == "S":
        return ImmutableMatrix([[c, -s, 0], [s, c, 0], [0, 0, e.eps]])
    return ImmutableMatrix([[c, s, 0], [s, -c, 0], [0, 0, e.eps]])


@lru_cache(maxsize=None)
def elements() -> Tuple[D6dElement, ...]:
    """The 24 elements in the order S_0, ..., S_11, P_0, ..., P_11 (S_0 = E, S_1 = S12,
    P_1 = C2'(15 deg)).  The parametrised matrices are checked to be exactly the closure of
    the two generators."""
    els = tuple(D6dElement("S", k) for k in range(N)) + tuple(D6dElement("P", k) for k in range(N))
    mats = {_parametrised_matrix(e) for e in els}
    if len(mats) != ORDER or mats != set(closure()):
        raise ValueError("the closure of the generators is not the parametrised D6d")
    return els


def identity() -> D6dElement:
    return elements()[0]


def index_of(e: D6dElement) -> int:
    return (0 if e.kind == "S" else N) + e.k


@lru_cache(maxsize=None)
def matrix(e: D6dElement) -> ImmutableMatrix:
    """The exact 3x3 matrix of the element (an element of the closure of the generators)."""
    elements()                                   # verifies the closure once
    return _parametrised_matrix(e)


@lru_cache(maxsize=None)
def _matrix_index() -> Dict[ImmutableMatrix, int]:
    return {matrix(e): index_of(e) for e in elements()}


def element_of_matrix(M: Matrix) -> D6dElement:
    """The element with the given exact matrix (KeyError if M is not in D6d)."""
    return elements()[_matrix_index()[_canon_matrix(M)]]


def det(e: D6dElement) -> sp.Expr:
    return _canon3(matrix(e).det())


def zz(e: D6dElement) -> sp.Expr:
    return matrix(e)[2, 2]


def is_proper(e: D6dElement) -> bool:
    return det(e) == 1


@lru_cache(maxsize=None)
def multiplication_table() -> Tuple[Tuple[int, ...], ...]:
    """mult[i][j] = index of g_i g_j in ``elements()``, from the exact matrix products."""
    mats = [matrix(e) for e in elements()]
    idx = _matrix_index()
    return tuple(tuple(idx[_canon_matrix(a * b)] for b in mats) for a in mats)


@lru_cache(maxsize=None)
def inverse_table() -> Tuple[int, ...]:
    mult = multiplication_table()
    return tuple(next(j for j in range(ORDER) if mult[i][j] == 0) for i in range(ORDER))


def inverse(e: D6dElement) -> D6dElement:
    return elements()[inverse_table()[index_of(e)]]


def compose(a: D6dElement, b: D6dElement) -> D6dElement:
    """The product a b (apply b first, then a)."""
    return elements()[multiplication_table()[index_of(a)][index_of(b)]]


def power(e: D6dElement, n: int) -> D6dElement:
    out = identity()
    for _ in range(n % (2 * N) if n >= 0 else 0):
        out = compose(out, e)
    if n < 0:
        return inverse(power(e, -n))
    return out


def element_order(e: D6dElement) -> int:
    """The smallest n >= 1 with g^n = E."""
    mult = multiplication_table()
    i, n, cur = index_of(e), 1, index_of(e)
    while cur != 0:
        cur = mult[cur][i]
        n += 1
    return n


# --------------------------------------------------------------------------- group facts
def has_inversion() -> bool:
    return INVERSION in _matrix_index()


def has_horizontal_mirror() -> bool:
    return SIGMA_H in _matrix_index()


def proper_rotation_orders() -> Dict[int, int]:
    """{order: number of proper rotations of that order}: {1: 1, 2: 7, 3: 2, 6: 2}."""
    out: Dict[int, int] = {}
    for e in elements():
        if is_proper(e):
            n = element_order(e)
            out[n] = out.get(n, 0) + 1
    return dict(sorted(out.items()))


def has_true_twelvefold_rotation() -> bool:
    """False: the only operation of order 12 is the rotoreflection S12 (and its odd powers)."""
    return any(is_proper(e) and element_order(e) == N for e in elements())


def mirror_direction_angles() -> Tuple[sp.Expr, ...]:
    """The in-plane directions contained in the six vertical mirror planes: j pi/6, j = 0..5
    (the framework edges), read off the matrices (an in-plane unit vector fixed together with z)."""
    return tuple(sorted({_fixed_line_angle(e) for e in elements() if _is_mirror(e)}))


def twofold_axis_angles() -> Tuple[sp.Expr, ...]:
    """The six in-plane two-fold axes: pi/12 + j pi/6, j = 0..5."""
    return tuple(sorted({_fixed_line_angle(e) for e in elements() if _is_twofold_in_plane(e)}))


def _is_mirror(e: D6dElement) -> bool:
    return det(e) == -1 and zz(e) == 1 and element_order(e) == 2


def _is_twofold_in_plane(e: D6dElement) -> bool:
    return det(e) == 1 and zz(e) == -1 and element_order(e) == 2


def _fixed_line_angle(e: D6dElement) -> sp.Expr:
    """The angle (in [0, pi)) of the in-plane unit vector fixed by a mirror or an in-plane
    two-fold rotation, verified exactly against the matrix."""
    a = e.line_angle % pi
    n = Matrix([sp.cos(a), sp.sin(a), 0])
    if not all(_is_zero(x) for x in (matrix(e) * n - n)):
        raise ValueError(f"{e.label} does not fix the direction {a}")
    return a


def group_facts() -> Dict[str, object]:
    """The facts checked in Appendix B: order 24, nine classes, no inversion, no horizontal
    mirror, no true twelve-fold rotation (S12 has order 12, the largest proper rotation
    order is 6)."""
    return {"order": len(elements()), "n_classes": len(conjugacy_classes()),
            "inversion": has_inversion(), "horizontal_mirror": has_horizontal_mirror(),
            "true_twelvefold_rotation": has_true_twelvefold_rotation(),
            "S12_order": element_order(D6dElement("S", 1)),
            "proper_rotation_orders": proper_rotation_orders(),
            "max_proper_rotation_order": max(proper_rotation_orders()),
            "mirror_directions_deg": [int(a * 180 / pi) for a in mirror_direction_angles()],
            "twofold_axes_deg": [int(a * 180 / pi) for a in twofold_axis_angles()]}


# --------------------------------------------------------------------------- classes
def _class_label(e: D6dElement) -> str:
    """Class label from the element type: S_k by min(k, 12 - k); P_k by the parity of k."""
    if e.kind == "P":
        return "C2'" if e.k % 2 else "sigma_d"
    r = min(e.k, N - e.k)
    return {0: "E", 1: "S12", 2: "C6", 3: "S4", 4: "C3", 5: "S12^5", 6: "C2"}[r]


def _conjugacy_classes(indices: Sequence[int], labels: Sequence[str]) -> Dict[str, Tuple[int, ...]]:
    """Conjugacy classes of the subgroup with the given element indices, computed from the
    multiplication table and labelled (every class must carry a single label)."""
    els = elements()
    mult = multiplication_table()
    inv = inverse_table()
    seen = set()
    classes: Dict[str, Tuple[int, ...]] = {}
    for i in indices:
        if i in seen:
            continue
        orbit = sorted({mult[mult[h][i]][inv[h]] for h in indices})
        seen.update(orbit)
        found = {_class_label(els[j]) for j in orbit}
        if len(found) != 1:
            raise ValueError(f"class {orbit} mixes labels {found}")
        classes[found.pop()] = tuple(orbit)
    if set(classes) != set(labels):
        raise ValueError(f"unexpected class structure {sorted(classes)}")
    return {c: classes[c] for c in labels}


@lru_cache(maxsize=None)
def conjugacy_classes() -> Dict[str, Tuple[int, ...]]:
    """The nine classes (label -> indices into ``elements()``), in the order ``CLASSES_D6D``."""
    cl = _conjugacy_classes(range(ORDER), CLASSES_D6D)
    if tuple(len(v) for v in cl.values()) != CLASS_SIZES_D6D:
        raise ValueError("unexpected class sizes")
    return cl


def class_of(e: D6dElement) -> str:
    i = index_of(e)
    for c, idx in conjugacy_classes().items():
        if i in idx:
            return c
    raise ValueError(e)


@lru_cache(maxsize=None)
def class_representatives() -> Tuple[D6dElement, ...]:
    """The first element of each class, in the order of ``CLASSES_D6D``."""
    els = elements()
    return tuple(els[idx[0]] for idx in conjugacy_classes().values())


# --------------------------------------------------------------------------- functions on the circle
def _in_plane_block(e: D6dElement) -> ImmutableMatrix:
    return matrix(e)[:2, :2]


@lru_cache(maxsize=None)
def function_matrix(m: int, e: D6dElement) -> ImmutableMatrix:
    """The exact 2x2 matrix of f -> f o g^-1 on span{cos m phi, sin m phi} (m >= 1; the 1x1
    identity for m = 0), column j = image of basis function j, derived from the in-plane block
    O of the matrix of g: with zeta = O_00 + i O_10 (e^{i theta} for the rotation by theta,
    e^{2 i alpha} for the reflection across the line at alpha) and zeta^m = c + i s the
    matrix is [[c, -s], [s, c]] (rotation by m theta) or [[c, s], [s, -c]] (reflection across
    the line at m alpha).  This is a representation of D6d; its trace is 2 cos(2 pi m k/12) on
    S_k and 0 on P_k."""
    if m < 0:
        raise ValueError("m must be >= 0")
    if m == 0:
        return ImmutableMatrix([[1]])
    O = _in_plane_block(e)
    zeta = O[0, 0] + sp.I * O[1, 0]
    c, s = (_canon3(x) for x in _canon3(zeta ** m).as_real_imag())
    d = _canon3(O.det())
    return ImmutableMatrix([[c, -d * s], [s, d * c]])


def function_character(m: int, e: D6dElement) -> sp.Expr:
    return _canon3(function_matrix(m, e).trace())


def _kron(A: Matrix, B: Matrix) -> Matrix:
    return Matrix(A.rows * B.rows, A.cols * B.cols,
                  lambda i, j: A[i // B.rows, j // B.cols] * B[i % B.rows, j % B.cols])


def _check_sector(sector: str):
    if sector not in SECTORS:
        raise ValueError(f"unknown sector {sector!r}; choose one of {SECTORS}")


def basis_functions(sector: str, m: int) -> Tuple:
    """The basis of the sector: scalars cos m phi, sin m phi (the constant 1 for m = 0) for the
    singlet; the triplet bases as 3-tuples (d_x, d_y, d_z) in the order
    cos m phi e_x, sin m phi e_x, cos m phi e_y, sin m phi e_y (in-plane) or
    cos m phi e_z, sin m phi e_z."""
    _check_sector(sector)
    funcs = (S(1),) if m == 0 else (sp.cos(m * ANGLE), sp.sin(m * ANGLE))
    if sector == "singlet":
        return funcs
    if sector == "triplet_inplane":
        return tuple((f, S(0), S(0)) for f in funcs) + tuple((S(0), f, S(0)) for f in funcs)
    return tuple((S(0), S(0), f) for f in funcs)


@lru_cache(maxsize=None)
def sector_matrix(sector: str, m: int, e: D6dElement) -> ImmutableMatrix:
    """The exact matrix of g on the sector (columns = images of the basis functions):
    F for the singlet (psi -> psi o g^-1); det(g) (O kron F) for the in-plane triplet and
    det(g) g_zz F for d_z (d -> det(g) g d o g^-1), F = ``function_matrix(m, g)`` and O the
    in-plane block of g."""
    _check_sector(sector)
    F = function_matrix(m, e)
    if sector == "singlet":
        return F
    if sector == "triplet_inplane":
        return _canon_matrix(det(e) * _kron(_in_plane_block(e), F))
    return _canon_matrix(det(e) * zz(e) * F)


def sector_character(sector: str, m: int) -> Tuple[sp.Expr, ...]:
    """The character of the sector on the classes of D6d."""
    return tuple(_canon3(sector_matrix(sector, m, e).trace()) for e in class_representatives())


def sector_decomposition(sector: str, m: int) -> Dict[str, int]:
    """Irrep content of the sector, from the character table."""
    return character_table_D6d().decompose(sector_character(sector, m))


@lru_cache(maxsize=None)
def isotypic_projector(sector: str, m: int, irrep: str) -> ImmutableMatrix:
    """P_Gamma = (d_Gamma/|G|) sum_g chi_Gamma(g) rho(g) on the sector (exact, idempotent)."""
    T = character_table_D6d()
    P = sp.zeros(sector_matrix(sector, m, identity()).rows)
    for e in elements():
        P += character(irrep, e) * sector_matrix(sector, m, e)
    P = _canon_matrix(P * T.dim(irrep) / ORDER)
    if _canon_matrix(P * P) != P:
        raise ValueError("projector is not idempotent")
    return P


def _combine(coeffs: Sequence, basis: Sequence):
    if isinstance(basis[0], tuple):
        return tuple(_canon3(sum(c * b[i] for c, b in zip(coeffs, basis))) for i in range(3))
    return _canon3(sum(c * b for c, b in zip(coeffs, basis)))


@lru_cache(maxsize=None)
def sector_basis(sector: str, m: int, irrep: str) -> Tuple:
    """Basis functions of the irrep inside the sector: the rows of the reduced row echelon form
    of the image of the isotypic projector, expressed in the basis functions (scalars for the
    singlet, 3-tuples (d_x, d_y, d_z) for the triplet).  Empty if the irrep does not occur;
    (multiplicity x dimension) functions otherwise."""
    P = isotypic_projector(sector, m, irrep)
    R, pivots = P.T.rref(iszerofunc=_is_zero)
    basis = basis_functions(sector, m)
    out = tuple(_combine([_canon3(x) for x in R.row(i)], basis) for i in range(len(pivots)))
    T = character_table_D6d()
    if len(out) != sector_decomposition(sector, m).get(irrep, 0) * T.dim(irrep):
        raise ValueError("rank of the projector disagrees with the multiplicity")
    return out


def sector_bases(sector: str, m: int) -> Dict[str, Tuple]:
    """{irrep: basis functions} for every irrep occurring in the sector."""
    return {irrep: sector_basis(sector, m, irrep) for irrep in sector_decomposition(sector, m)}


# --------------------------------------------------------------------------- character table
def _one_dim_character(name: str, e: D6dElement) -> sp.Expr:
    """A1 = 1, B1 = det g, B2 = g_zz, A2 = det g . g_zz (each is a homomorphism to {+-1})."""
    if name == "A1":
        return S(1)
    if name == "A2":
        return _canon3(det(e) * zz(e))
    if name == "B1":
        return det(e)
    if name == "B2":
        return zz(e)
    raise KeyError(name)


@dataclass(frozen=True)
class D6dCharacterTable(CharacterTable):
    """``groups.CharacterTable`` with the inner product taken in Q(sqrt3)."""

    def inner(self, u: Sequence, v: Sequence) -> sp.Expr:
        return _canon3(sum(s * sp.conjugate(a) * b for s, a, b in zip(self.sizes, u, v)) / self.order)


@lru_cache(maxsize=None)
def character_table_D6d() -> D6dCharacterTable:
    """The character table of D6d, classes in the order ``CLASSES_D6D``:
    E, 2 S12, 2 C6, 2 S4, 2 C3, 2 S12^5, C2, 6 C2', 6 sigma_d.  The one-dimensional rows are
    read off the matrices (``_one_dim_character``), the E_m rows are the traces of the exact
    matrices on span{cos m phi, sin m phi}; orthonormality is checked."""
    reps = class_representatives()
    chars: Dict[str, Tuple[sp.Expr, ...]] = {}
    for name in ("A1", "A2", "B1", "B2"):
        chars[name] = tuple(_one_dim_character(name, e) for e in reps)
    for m in range(1, N // 2):
        chars[f"E{m}"] = tuple(function_character(m, e) for e in reps)
    T = D6dCharacterTable("D6d", CLASSES_D6D, CLASS_SIZES_D6D, chars)
    if not T.is_orthonormal():
        raise ValueError("D6d character table is not orthonormal")
    return T


def character(irrep: str, e: D6dElement) -> sp.Expr:
    """chi_Gamma(g) for an element g."""
    return character_table_D6d().chars[irrep][CLASSES_D6D.index(class_of(e))]


def is_class_function(values: Sequence) -> bool:
    return all(len({values[i] for i in idx}) == 1 for idx in conjugacy_classes().values())


def is_one_dim_representation(irrep: str) -> bool:
    """chi(ab) = chi(a) chi(b) on all 24 x 24 products (for a one-dimensional irrep)."""
    els = elements()
    mult = multiplication_table()
    chi = [character(irrep, e) for e in els]
    return all(chi[mult[i][j]] == chi[i] * chi[j] for i in range(ORDER) for j in range(ORDER))


# --------------------------------------------------------------------------- Table 10
def table10() -> List[Dict[str, object]]:
    """One row per irrep: the singlet basis functions (m = 0, 2, 4, 6) and the triplet basis
    functions (in-plane and d_z, m = 1, 3, 5) that transform as the irrep."""
    rows = []
    for irrep in IRREPS_D6D:
        singlet = [{"m": m, "functions": sector_basis("singlet", m, irrep)}
                   for m in SINGLET_M if irrep in sector_decomposition("singlet", m)]
        triplet = []
        for m in TRIPLET_M:
            for sector, tag in (("triplet_inplane", "in-plane"), ("triplet_z", "d_z")):
                if irrep in sector_decomposition(sector, m):
                    triplet.append({"m": m, "sector": tag, "functions": sector_basis(sector, m, irrep)})
        rows.append({"irrep": irrep, "singlet": singlet, "triplet": triplet})
    return rows


# --------------------------------------------------------------------------- antisymmetric spin-orbit coupling
def asoc_A1_content(mmax: int = 5) -> Dict[int, Dict[str, int]]:
    """{m: {"inplane": multiplicity of A1, "z": ...}} for the odd harmonics m <= mmax: the
    invariant (A1) content of an odd axial vector field g(k) on the circle.  Within Table 10's
    range only the in-plane m = 5 sector contains A1 (once); no d_z sector with odd m does."""
    return {m: {"inplane": sector_decomposition("triplet_inplane", m).get("A1", 0),
                "z": sector_decomposition("triplet_z", m).get("A1", 0)}
            for m in range(1, mmax + 1, 2)}


def asoc_vector() -> Tuple[sp.Expr, sp.Expr, sp.Expr]:
    """The A1 basis function of the in-plane m = 5 sector, (sin 5 phi, cos 5 phi, 0): the only
    invariant odd axial vector with |m| <= 6, hence the form of the antisymmetric spin-orbit
    vector g(k) on the circle."""
    (g,) = sector_basis("triplet_inplane", 5, "A1")
    return g


# --------------------------------------------------------------------------- restriction to D2d
def subgroup_generated(gens: Sequence[D6dElement]) -> Tuple[int, ...]:
    """Indices of the subgroup generated by the given elements."""
    mult = multiplication_table()
    found = {0}
    frontier = [0]
    gi = [index_of(g) for g in gens]
    while frontier:
        new = []
        for a in frontier:
            for g in gi:
                b = mult[a][g]
                if b not in found:
                    found.add(b)
                    new.append(b)
        frontier = new
    return tuple(sorted(found))


@lru_cache(maxsize=None)
def d2d_elements() -> Tuple[int, ...]:
    """D2d = -42m: the subgroup of order 8 generated by S4 = S12^3 and the two-fold axis at
    15 deg (indices into ``elements()``)."""
    sub = subgroup_generated((D6dElement("S", 3), D6dElement("P", 1)))
    if len(sub) != 8:
        raise ValueError("D2d should have order 8")
    return sub


@lru_cache(maxsize=None)
def d2d_classes() -> Dict[str, Tuple[int, ...]]:
    """The five classes of D2d: E, 2 S4, C2, 2 C2' (axes at 15 and 105 deg), 2 sigma_d (planes
    containing 60 and 150 deg)."""
    cl = _conjugacy_classes(d2d_elements(), CLASSES_D2D)
    if tuple(len(v) for v in cl.values()) != CLASS_SIZES_D2D:
        raise ValueError("unexpected D2d class sizes")
    return cl


@lru_cache(maxsize=None)
def character_table_D2d() -> D6dCharacterTable:
    """The character table of D2d built like that of D6d: A1 = 1, A2 = det . g_zz, B1 = det,
    B2 = g_zz, E = trace of the in-plane block (the polar vector (x, y))."""
    els = elements()
    reps = [els[idx[0]] for idx in d2d_classes().values()]
    chars = {name: tuple(_one_dim_character(name, e) for e in reps) for name in ("A1", "A2", "B1", "B2")}
    chars["E"] = tuple(_canon3(_in_plane_block(e).trace()) for e in reps)
    T = D6dCharacterTable("D2d", CLASSES_D2D, CLASS_SIZES_D2D, chars)
    if not T.is_orthonormal():
        raise ValueError("D2d character table is not orthonormal")
    return T


def restriction_to_D2d(irrep: str) -> Dict[str, int]:
    """Gamma restricted to D2d, decomposed: the character of Gamma on the D2d class
    representatives, decomposed with the D2d table."""
    els = elements()
    reps = [els[idx[0]] for idx in d2d_classes().values()]
    return character_table_D2d().decompose(tuple(character(irrep, e) for e in reps))


def restriction_table_D2d() -> Dict[str, Dict[str, int]]:
    """A1 -> A1, A2 -> A2, B1 -> B1, B2 -> B2, E1 -> E, E2 -> B1 + B2, E3 -> E, E4 -> A1 + A2,
    E5 -> E."""
    return {irrep: restriction_to_D2d(irrep) for irrep in IRREPS_D6D}


# --------------------------------------------------------------------------- in-plane field orbit
def _reduce_angle(a) -> sp.Expr:
    """An angle that is a rational multiple of pi, reduced to [0, 2 pi)."""
    q = sp.Rational(sp.nsimplify(a / pi))
    return (q % 2) * pi


def axial_image_angle(e: D6dElement, alpha) -> sp.Expr:
    """The polar angle of det(g) g H for the in-plane axial vector H = (cos alpha, sin alpha, 0):
    alpha + 2 pi k/12 for S_k and 2 (k pi/12) - alpha for P_k (the induced map of the polar
    angle), plus pi when g is improper (det g = -1)."""
    a = e.act(alpha) + (0 if is_proper(e) else pi)
    return _reduce_angle(a)


def field_orbit(alpha=0, reversal: bool = True) -> Tuple[sp.Expr, ...]:
    """The orbit of the field direction alpha (a rational multiple of pi) under D6d acting on
    axial vectors, with H -> -H included by default: the sorted distinct angles in [0, 2 pi).
    For alpha = 0 (a framework edge) these are the twelve multiples of pi/6."""
    angles = {axial_image_angle(e, alpha) for e in elements()}
    if reversal:
        angles |= {_reduce_angle(a + pi) for a in angles}
    return tuple(sorted(angles))


def field_angle_period() -> sp.Expr:
    """The period of in-plane field-angle dependences: the smallest positive rotation of the
    axial in-plane vector realised by the group (the S_k act as rotations by 2 pi k/12, plus
    pi when improper) together with H -> -H; this is pi/6 (30 deg)."""
    shifts = {axial_image_angle(e, 0) for e in elements() if e.kind == "S"} | {pi}
    return min(a for a in shifts if a > 0)


# --------------------------------------------------------------------------- formatting
def format_decomposition(dec: Dict[str, int]) -> str:
    return character_table_D6d().format(dec)


def format_function(f) -> object:
    """A basis function as plain data: a string for a scalar, a list of three strings for a
    d-vector (sympy ``str`` form, e.g. 'cos(5*phi)')."""
    if isinstance(f, tuple):
        return [str(c) for c in f]
    return str(f)


def format_character_table(T: CharacterTable | None = None) -> Dict[str, object]:
    """{"classes": [...], "sizes": [...], "rows": [{"irrep": name, "chars": [str, ...]}]}."""
    T = T or character_table_D6d()
    return {"classes": list(T.classes), "sizes": list(T.sizes),
            "rows": [{"irrep": name, "chars": [str(c) for c in row]} for name, row in T.chars.items()]}


def format_sector(sector: str, m: int) -> Dict[str, object]:
    """{"m": m, "irreps": "B1 + B2 + E4", "basis": {"B1": [["cos(phi)", "sin(phi)", "0"]], ...}}."""
    return {"m": m, "irreps": format_decomposition(sector_decomposition(sector, m)),
            "basis": {irrep: [format_function(f) for f in funcs]
                      for irrep, funcs in sector_bases(sector, m).items()}}


def format_table10() -> List[Dict[str, object]]:
    return [{"irrep": r["irrep"],
             "singlet": [{"m": s["m"], "functions": [format_function(f) for f in s["functions"]]}
                         for s in r["singlet"]],
             "triplet": [{"m": t["m"], "sector": t["sector"],
                          "functions": [format_function(f) for f in t["functions"]]}
                         for t in r["triplet"]]}
            for r in table10()]


def format_elements() -> List[Dict[str, object]]:
    return [{"index": index_of(e), "label": e.label, "class": class_of(e), "det": int(det(e)),
             "zz": int(zz(e)), "order": element_order(e)} for e in elements()]


def summary() -> Dict[str, object]:
    """Everything of Appendix B as plain data (for results.json / the LaTeX emitter)."""
    T = character_table_D6d()
    return {"order": T.order, "irreps": list(T.irreps),
            "generators": {"S12": [[str(x) for x in row] for row in generator_S12().tolist()],
                           "C2prime_15deg": [[str(x) for x in row] for row in generator_C2prime().tolist()]},
            "facts": group_facts(),
            "elements": format_elements(),
            "character_table": format_character_table(),
            "singlet": [format_sector("singlet", m) for m in SINGLET_M],
            "triplet_inplane": [format_sector("triplet_inplane", m) for m in TRIPLET_M],
            "triplet_z": [format_sector("triplet_z", m) for m in TRIPLET_M],
            "table10": format_table10(),
            "asoc": {"A1_content": {str(m): v for m, v in asoc_A1_content().items()},
                     "g": format_function(asoc_vector())},
            "restriction_D2d": {"classes": list(CLASSES_D2D), "sizes": list(CLASS_SIZES_D2D),
                                "character_table": format_character_table(character_table_D2d()),
                                "table": {k: character_table_D2d().format(v)
                                          for k, v in restriction_table_D2d().items()}},
            "field_orbit": {"angles_deg": [int(a * 180 / pi) for a in field_orbit(0)],
                            "period_deg": int(field_angle_period() * 180 / pi)}}
