"""Restriction of the irreps of I to its subgroups (Table 5 and Section 7 of the paper).

Physics
-------
An approximant crystal or a uniaxial strain lowers the icosahedral point group I to one
of its maximal rotation subgroups: the tetrahedral group T (cubic approximants), the
dihedral groups D5 and D3 (five-fold / three-fold uniaxial strain) and D2 (three
orthogonal two-fold axes, the "orthorhombic" case).  A pairing channel that transforms
as an irrep Gamma of I then splits into irreps of the subgroup; the splitting is
Table 5 of the paper.  Restriction to the cyclic groups C5, C3, C2 about a single axis
is what decides whether a gap function is forced to vanish on that axis (Section 7:
a channel that contains no trivial character of the C_n about an axis has an enforced
node there).

What is computed
----------------
* ``restrict(irrep, "T" | "D5" | "D3")`` -- by characters, exactly as the legacy
  ``restrict()`` of ``ih_basis.py``: the character of the I-irrep on a subgroup class
  is its value on the I-class with the same rotation angle (rotation classes fuse),
  and the multiplicity of a subgroup irrep chi_s is <chi_s, chi>/<chi_s, chi_s>.  The
  division by the norm matters for the real two-dimensional representation E = 1E + 2E
  of T, which has norm 2.
* ``restrict(irrep, "D2")`` -- from the parities of the basis functions of Section 3.3
  (``harmonics.paper_basis_functions``) at the lowest l of the irrep, as stated in the
  caption of Table 5: each basis function is an eigenfunction of the three coordinate
  two-fold rotations C2x, C2y, C2z, and the sign pattern names the D2 irrep
  (A even under all, B1 invariant under C2z only, B2 under C2y only, B3 under C2x only).
  The same restriction is also computed by characters; because the three C2's are
  conjugate in I, characters can only fix the number of A's and the total number of
  B's (B1, B2, B3 are forced to have equal multiplicity), and the two results are
  checked against each other.
* ``restrict_to_cyclic(irrep, n)`` -- the multiplicities of the characters chi_m,
  chi_m(g^p) = exp(2 pi i m p / n), of the cyclic group C_n generated by the C5 about
  (phi, 1, 0), the C3 about (1, 1, 1) or the C2 about z, computed exactly from the
  characters of I on the powers of the generator (multiplication table of I).
  ``has_trivial_character`` is the enforced-node criterion of Section 7: G restricted
  to C5 contains no chi_0.
* ``restriction_table()`` / ``restriction_table_data()`` -- Table 5 as nested dicts and
  as plain rows of strings ("A1 + 2E") for the LaTeX emitter.

The subgroups themselves are generated inside I (``subgroup(name).elements``) so the
class sizes used in the character tables are read off the group, not assumed.  All
arithmetic is exact over Q(sqrt5).
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from typing import Dict, List, Sequence, Tuple

import sympy as sp
from sympy import S

from ._exact import PHI, canon
from .groups import (CHAR_I, CLASSES_I, IRREPS_I, CharacterTable, Rotation, generate_subgroup,
                     icosahedral_group, rotation_about, twofold_axes)
from .harmonics import act, paper_basis_functions

SUBGROUPS = ("T", "D5", "D3", "D2")          # column order of Table 5
CYCLIC_ORDERS = (5, 3, 2)                    # C5, C3, C2 of Section 7

COS72 = canon((PHI - 1) / 2)                 # cos 72 deg
COS144 = canon(-PHI / 2)                     # cos 144 deg

# Subgroup classes: (label, I-class with the same rotation angle), in table order.
# For T the two complex classes of three-fold rotations are fused (real table);
# for D2 the three two-fold rotations are separate classes (the group is abelian).
_CLASS_FUSION: Dict[str, Tuple[Tuple[str, str], ...]] = {
    "T": (("E", "E"), ("C3", "C3"), ("C2", "C2")),
    "D5": (("E", "E"), ("C5", "C5"), ("C5^2", "C5^2"), ("C2'", "C2")),
    "D3": (("E", "E"), ("C3", "C3"), ("C2'", "C2")),
    "D2": (("E", "E"), ("C2x", "C2"), ("C2y", "C2"), ("C2z", "C2")),
}

# Standard character tables of the subgroups (columns in the class order above).
_SUBGROUP_CHARS: Dict[str, Dict[str, Tuple[sp.Expr, ...]]] = {
    "T": {"A": (S(1), S(1), S(1)),
          "E": (S(2), S(-1), S(2)),          # the real rep 1E + 2E (norm 2)
          "T": (S(3), S(0), S(-1))},
    "D5": {"A1": (S(1), S(1), S(1), S(1)),
           "A2": (S(1), S(1), S(1), S(-1)),
           "E1": (S(2), canon(2 * COS72), canon(2 * COS144), S(0)),
           "E2": (S(2), canon(2 * COS144), canon(2 * COS72), S(0))},
    "D3": {"A1": (S(1), S(1), S(1)),
           "A2": (S(1), S(1), S(-1)),
           "E": (S(2), S(-1), S(0))},
    "D2": {"A": (S(1), S(1), S(1), S(1)),
           "B1": (S(1), S(-1), S(-1), S(1)),   # invariant under C2z only
           "B2": (S(1), S(-1), S(1), S(-1)),   # invariant under C2y only
           "B3": (S(1), S(1), S(-1), S(-1))},  # invariant under C2x only
}

# D2 label from the parities (under C2x, C2y, C2z) of a basis function.
D2_LABEL_OF_PARITIES: Dict[Tuple[int, int, int], str] = {
    (1, 1, 1): "A", (-1, -1, 1): "B1", (-1, 1, -1): "B2", (1, -1, -1): "B3"}

# Lowest l at which each irrep of I occurs in the harmonics (Table 3); the basis
# functions of Section 3.3 at that l are used for the D2 parities.
LOWEST_L: Dict[str, int] = {"A": 0, "T1": 1, "H": 2, "T2": 3, "G": 3}

# Generators of the cyclic groups of Section 7: (axis, class) -> groups.rotation_about.
CYCLIC_GENERATORS: Dict[int, Tuple[Tuple[sp.Expr, ...], str]] = {
    5: ((PHI, S(1), S(0)), "C5"), 3: ((S(1), S(1), S(1)), "C3"), 2: ((S(0), S(0), S(1)), "C2")}


# --------------------------------------------------------------------------- subgroups of I
@dataclass(frozen=True)
class Subgroup:
    """A subgroup of I generated inside the group: its elements (indices into
    ``icosahedral_group().rotations``), its classes (label -> element indices), the
    I-class each class fuses into, and its character table."""
    name: str
    generators: Tuple[int, ...]
    elements: Tuple[int, ...]
    classes: Dict[str, Tuple[int, ...]]
    fusion: Dict[str, str]
    table: CharacterTable

    @property
    def order(self) -> int:
        return len(self.elements)


def _c2(axis) -> Rotation:
    return rotation_about(axis, "C2")


def _perpendicular_twofold(axis: Sequence) -> Rotation:
    """The first two-fold rotation of I (in the fixed order of ``twofold_axes``) whose
    axis is exactly perpendicular to the given axis."""
    a = sp.Matrix([sp.sympify(c) for c in axis])
    for b in twofold_axes():
        if canon((a.T * b)[0]) == 0:
            return rotation_about(b, "C2")
    raise ValueError(f"no two-fold axis perpendicular to {list(axis)}")


def _generators(name: str) -> Tuple[int, ...]:
    """Generators of the standard embedding of each subgroup: T = <C2x, C2z, C3(1,1,1)>,
    D5 = <C5(phi,1,0), C2 perp>, D3 = <C3(1,1,1), C2 perp>, D2 = <C2x, C2z>."""
    if name == "T":
        return (_c2((1, 0, 0)).index, _c2((0, 0, 1)).index, rotation_about((1, 1, 1), "C3").index)
    if name == "D5":
        return (rotation_about((PHI, 1, 0), "C5").index, _perpendicular_twofold((PHI, 1, 0)).index)
    if name == "D3":
        return (rotation_about((1, 1, 1), "C3").index, _perpendicular_twofold((1, 1, 1)).index)
    if name == "D2":
        return (_c2((1, 0, 0)).index, _c2((0, 0, 1)).index)
    raise ValueError(f"unknown subgroup {name!r}; expected one of {SUBGROUPS}")


@lru_cache(maxsize=None)
def subgroup(name: str) -> Subgroup:
    """The subgroup T, D5, D3 or D2 of I in its standard embedding (two-fold axes along
    x, y, z; three-fold axis (1,1,1); five-fold axis (phi,1,0)), with its classes and
    character table.  Class sizes are counted in the group."""
    G = icosahedral_group()
    gens = _generators(name)
    elems = generate_subgroup(gens)
    fusion = dict(_CLASS_FUSION[name])
    if name == "D2":
        classes = {"E": (0,), "C2x": (_c2((1, 0, 0)).index,), "C2y": (_c2((0, 1, 0)).index,),
                   "C2z": (_c2((0, 0, 1)).index,)}
    else:
        classes = {lab: tuple(i for i in elems if G.class_of(i) == icls) for lab, icls in fusion.items()}
    assert sum(len(v) for v in classes.values()) == len(elems), (name, classes)
    assert set(i for v in classes.values() for i in v) == set(elems), name
    table = CharacterTable(name, tuple(classes), tuple(len(classes[c]) for c in classes),
                           dict(_SUBGROUP_CHARS[name]))
    return Subgroup(name, gens, elems, classes, fusion, table)


def character_table(name: str) -> CharacterTable:
    """Character table of the subgroup (classes E, C3, C2 for T; E, C5, C5^2, C2' for D5;
    E, C3, C2' for D3; E, C2x, C2y, C2z for D2)."""
    return subgroup(name).table


# --------------------------------------------------------------------------- restriction by characters
def restricted_character(irrep: str, name: str) -> Tuple[sp.Expr, ...]:
    """The character of the I-irrep on the classes of the subgroup: its value on the
    I-class with the same rotation angle (Table 1)."""
    sub = subgroup(name)
    return tuple(CHAR_I.chars[irrep][CLASSES_I.index(sub.fusion[c])] for c in sub.table.classes)


def _multiplicities(table: CharacterTable, chars: Sequence) -> Dict[str, int]:
    """Multiplicities <chi_s, chi>/<chi_s, chi_s> of the rows of ``table`` in the class
    function ``chars`` (legacy ``restrict``); keys with nonzero multiplicity only, in
    table order."""
    out: Dict[str, int] = {}
    for sname, row in table.chars.items():
        norm = table.inner(row, row)
        m = canon(table.inner(row, chars) / norm)
        if m != 0:
            if not m.is_Integer or m < 0:
                raise ValueError(f"non-integral multiplicity {m} of {sname} in {table.name}")
            out[sname] = int(m)
    return out


def restrict_by_characters(irrep: str, name: str) -> Dict[str, int]:
    """Restriction Gamma|_K of an irrep of I to K in {T, D5, D3, D2} by characters.

    Returns {subgroup irrep: multiplicity}.  For D2 the three B's come out with equal
    multiplicity (chi(E) - chi(C2))/4 because the three two-fold rotations are
    conjugate in I; only ``restrict_D2_by_parities`` attaches the labels to functions."""
    sub = subgroup(name)
    dec = _multiplicities(sub.table, restricted_character(irrep, name))
    if sum(m * sub.table.dim(k) for k, m in dec.items()) != CHAR_I.dim(irrep):
        raise ValueError(f"dimension mismatch in {irrep}|{name}: {dec}")
    return dec


def d2_character_counts(irrep: str) -> Dict[str, int]:
    """What characters alone say about Gamma|_D2: the number of A's and the total number
    of B's, {"A": n_A, "B": n_B} (zero entries omitted)."""
    dec = restrict_by_characters(irrep, "D2")
    out = {}
    if dec.get("A", 0):
        out["A"] = dec["A"]
    n_b = sum(m for k, m in dec.items() if k != "A")
    if n_b:
        out["B"] = n_b
    return out


# --------------------------------------------------------------------------- D2 by parities
def lowest_l_basis(irrep: str) -> Dict[str, sp.Expr]:
    """The basis functions of Section 3.3 at the lowest l of the irrep (Table 3):
    A: the constant 1 (l=0); T1: x, y, z (l=1); H: the five l=2 quadratics;
    T2: f_x, f_y, f_z (l=3); G: g_x, g_y, g_z, xyz (l=3)."""
    l = LOWEST_L[irrep]
    if l == 0:
        return {"1": S(1)}
    return dict(paper_basis_functions()[(l, irrep)])


@lru_cache(maxsize=None)
def coordinate_twofolds() -> Tuple[Rotation, Rotation, Rotation]:
    """The rotations C2x, C2y, C2z of I about the coordinate axes (the group D2)."""
    return (_c2((1, 0, 0)), _c2((0, 1, 0)), _c2((0, 0, 1)))


def d2_parities(f) -> Tuple[int, int, int]:
    """Parities (+-1) of a polynomial f under C2x, C2y, C2z, i.e. the signs in
    rho(C2) f = +- f.  Raises if f is not a parity eigenfunction."""
    out = []
    for r in coordinate_twofolds():
        g = act(r.matrix, f)
        if sp.expand(g - f) == 0:
            out.append(1)
        elif sp.expand(g + f) == 0:
            out.append(-1)
        else:
            raise ValueError(f"{f} is not an eigenfunction of the two-fold rotation about {list(r.axis)}")
    return tuple(out)


def d2_labels(irrep: str) -> Dict[str, str]:
    """D2 irrep label (A, B1, B2, B3) of every lowest-l basis function of the irrep."""
    return {name: D2_LABEL_OF_PARITIES[d2_parities(f)] for name, f in lowest_l_basis(irrep).items()}


def restrict_D2_by_parities(irrep: str) -> Dict[str, int]:
    """Gamma|_D2 from the parities of the basis functions (caption of Table 5):
    {label: multiplicity} in the order A, B1, B2, B3 (zero entries omitted)."""
    labels = list(d2_labels(irrep).values())
    dec = {lab: labels.count(lab) for lab in ("A", "B1", "B2", "B3") if labels.count(lab)}
    if sum(dec.values()) != CHAR_I.dim(irrep):
        raise ValueError(f"{irrep}: {sum(dec.values())} basis functions for dimension {CHAR_I.dim(irrep)}")
    return dec


def d2_is_consistent(irrep: str) -> bool:
    """True if the parity and the character computations of Gamma|_D2 agree: same
    number of A's, same total number of B's, and each B_i multiplicity equal to the
    (common) value (chi(E) - chi(C2))/4 given by characters."""
    par = restrict_D2_by_parities(irrep)
    chars = restrict_by_characters(irrep, "D2")
    counts = d2_character_counts(irrep)
    same_a = par.get("A", 0) == counts.get("A", 0)
    same_b = sum(m for k, m in par.items() if k != "A") == counts.get("B", 0)
    each_b = all(par.get(b, 0) == chars.get(b, 0) for b in ("B1", "B2", "B3"))
    return same_a and same_b and each_b


# --------------------------------------------------------------------------- public restriction
def restrict(irrep: str, name: str) -> Dict[str, int]:
    """Gamma|_K for Gamma in {A, T1, T2, G, H} and K in {T, D5, D3, D2}: {K-irrep: multiplicity}.

    T, D5, D3 are done by characters; D2 by the parities of the basis functions, checked
    against the character count (ValueError if they disagree)."""
    if irrep not in IRREPS_I:
        raise ValueError(f"unknown irrep {irrep!r}; expected one of {IRREPS_I}")
    if name == "D2":
        if not d2_is_consistent(irrep):
            raise ValueError(f"{irrep}|D2: parities {restrict_D2_by_parities(irrep)} vs "
                             f"characters {restrict_by_characters(irrep, 'D2')}")
        return restrict_D2_by_parities(irrep)
    return restrict_by_characters(irrep, name)


def format_decomposition(dec: Dict[str, int], plus: str = " + ") -> str:
    """'A1 + 2E' style string of a decomposition dict (in the dict's order)."""
    return plus.join(f"{m if m > 1 else ''}{k}" for k, m in dec.items() if m)


@lru_cache(maxsize=None)
def restriction_table() -> Dict[str, Dict[str, Dict[str, int]]]:
    """Table 5 of the paper: {irrep: {subgroup: decomposition}} with rows A, T1, T2, G, H
    and columns T, D5, D3, D2."""
    return {irr: {name: restrict(irr, name) for name in SUBGROUPS} for irr in IRREPS_I}


def restriction_table_rows() -> List[Dict[str, str]]:
    """Table 5 as plain rows of strings: [{"irrep": "H", "T": "E + T", "D5": ..., ...}, ...]."""
    tab = restriction_table()
    return [{"irrep": irr, **{name: format_decomposition(tab[irr][name]) for name in SUBGROUPS}}
            for irr in IRREPS_I]


def restriction_table_data() -> Dict[str, object]:
    """Plain data for a LaTeX emitter: {"columns": [...], "rows": [...], "d2_labels": {...}}."""
    return {"columns": ["irrep", *SUBGROUPS],
            "rows": restriction_table_rows(),
            "d2_labels": {irr: dict(d2_labels(irr)) for irr in IRREPS_I}}


# --------------------------------------------------------------------------- cyclic subgroups (Section 7)
def cyclic_generator(n: int) -> Rotation:
    """The generator of C_n: the C5 about (phi, 1, 0), the C3 about (1, 1, 1) or the C2
    about z (the axes used throughout the paper)."""
    if n not in CYCLIC_GENERATORS:
        raise ValueError(f"no cyclic subgroup C{n} in the table; n must be one of {tuple(CYCLIC_GENERATORS)}")
    axis, cls = CYCLIC_GENERATORS[n]
    return rotation_about(axis, cls)


@lru_cache(maxsize=None)
def cyclic_powers(n: int) -> Tuple[int, ...]:
    """Indices of g^0, g^1, ..., g^(n-1) for the generator g of C_n (multiplication table
    of I); checks g^n = E."""
    G = icosahedral_group()
    g = cyclic_generator(n).index
    powers = [0]
    for _ in range(n - 1):
        powers.append(G.mult[powers[-1]][g])
    assert G.mult[powers[-1]][g] == 0, n
    return tuple(powers)


def cyclic_character(m: int, n: int) -> Tuple[sp.Expr, ...]:
    """The character chi_m of C_n on g^0, ..., g^(n-1): chi_m(g^p) = exp(2 pi i m p / n)."""
    return tuple(sp.exp(2 * sp.pi * sp.I * m * p / n) for p in range(n))


def restrict_to_cyclic(irrep: str, n: int) -> Dict[int, int]:
    """Multiplicities {m: n_m} of the characters chi_m (m mod n) of C_n in the I-irrep,
    n_m = (1/n) sum_p conj(chi_m(g^p)) chi_Gamma(g^p), exact (zero entries omitted)."""
    if irrep not in IRREPS_I:
        raise ValueError(f"unknown irrep {irrep!r}; expected one of {IRREPS_I}")
    G = icosahedral_group()
    chi = [G.character(irrep, i) for i in cyclic_powers(n)]
    out: Dict[int, int] = {}
    for m in range(n):
        s = sum(sp.conjugate(c_m) * c for c_m, c in zip(cyclic_character(m, n), chi)) / n
        s = sp.expand(sp.expand_complex(s.rewrite(sp.cos)))
        if sp.im(s) != 0:
            raise ValueError(f"non-real multiplicity {s} of chi_{m} in {irrep}|C{n}")
        val = canon(sp.re(s))
        if not val.is_Integer or val < 0:
            raise ValueError(f"non-integral multiplicity {val} of chi_{m} in {irrep}|C{n}")
        if val != 0:
            out[m] = int(val)
    if sum(out.values()) != CHAR_I.dim(irrep):
        raise ValueError(f"dimension mismatch in {irrep}|C{n}: {out}")
    return out


def has_trivial_character(irrep: str, n: int) -> bool:
    """Enforced-node criterion of Section 7: does Gamma|_{C_n} contain chi_0?  If not,
    every gap function in the channel vanishes on the n-fold axis."""
    return restrict_to_cyclic(irrep, n).get(0, 0) > 0


def format_cyclic(dec: Dict[int, int], plus: str = " + ") -> str:
    """'chi_0 + 2chi_1' style string of a C_n decomposition."""
    return plus.join(f"{m if m > 1 else ''}chi_{k}" for k, m in dec.items() if m)


def cyclic_table() -> Dict[str, Dict[int, Dict[int, int]]]:
    """{irrep: {n: Gamma|_{C_n}}} for n = 5, 3, 2."""
    return {irr: {n: restrict_to_cyclic(irr, n) for n in CYCLIC_ORDERS} for irr in IRREPS_I}


def cyclic_table_rows() -> List[Dict[str, str]]:
    """Section 7 data as plain rows: [{"irrep": "G", "C5": "chi_1 + chi_2 + chi_3 + chi_4",
    "C3": ..., "C2": ..., "node_on_C5": "yes"/"no", ...}, ...]."""
    tab = cyclic_table()
    rows = []
    for irr in IRREPS_I:
        row = {"irrep": irr}
        for n in CYCLIC_ORDERS:
            row[f"C{n}"] = format_cyclic(tab[irr][n])
        for n in CYCLIC_ORDERS:
            row[f"node_on_C{n}"] = "no" if tab[irr][n].get(0, 0) else "yes"
        rows.append(row)
    return rows
